import './globals.css'
import { Poppins } from 'next/font/google'

import Header from './components/Header/Header'
import Footer from './components/Footer/Footer'


const poppins = Poppins({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin']
})

export const metadata = {
  title: 'Softypy assignment',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Header/>
        <main className='container'>
          {children}
        </main>
        <Footer/>
      </body>
    </html>
  )
}
